### PR TITLE
Working implementation of local backend stored data

### PR DESCRIPTION
**Pull request by CptFubar**
After merging my local_backend branch into master i resolved the conflicts that occurred because of my badly implemented error handling implementation by using all origin master files instead of local. 

Non the less, i had updated the error handling a while back to use push_error method instead of just a prints statement to appear in the logs, this way they are logged in the log file and are helpful in debugging inside the Godot editor and debug window.

This branch features a new login screen that offers a rudimentary backend choice that can be further expanded into a detailed configuration of the implemented backends eg. connection strings to existing servers, multiple local accounts etc.

Another implemented feature is a local config file that stores all the settings options and is loaded upon starting the app.
It is implemented through a new singleton class "app_manager" that manages the applications configuration and startup values.

### CODE REVIEW

**Comment by alfredbaudisch** [comment]
@CptFubar I'm so bad at managing my 10.000 personal projects, sorry for leaving this hanging. I'll try to review it soon!

**Comment by CptFubar** [comment]
Doing some house keeping, i am closing this pull request since it does not fix a bug or is any important feature.

**Comment by alfredbaudisch** [comment]
Re-opening to merge it. Again, sorry for not answering earlier - I wrangle between way too many projects.

**Comment by alfredbaudisch** [comment]
Thanks a lot for the contribution! This is great. I'm updating the README with the new option for the local storage.

**Comment by alfredbaudisch** [comment]
Unfortunately, after further testing I found a breaking bug with this implementation, see #28.

In any case, I left the local backend implementation in [its own branch](https://github.com/alfredbaudisch/Godello/tree/local-backend), since it adds a lot of value (until me or someone fixes #28, then I'll merge it into master).

**Pull request merged**
