### PR TITLE
Refactoring code according to Godot coding style guide.

### PR DESCRIPTION
**Pull request by CptFubar**
Hi, i followed this project for some time and wanted to contribute with this pull request.
I implemented a working version with a local backend for a single user. 

In preparation for this i tried to refactor the code as mentioned in one of the issues #10 according to Godot's coding style guide, including the renaming of the files to snake_case. 

Additionally i dealt with all the existing warnings mentioned in issue #13 by either add "ignore" comments in case of signals or implemented a simple error logging system for unused return values.

Finally i added a .gdignore file to the doc folder so it won't be visible in the Editor and ignored by the importer.

I hope this project is still alive and will see further development. It is a great idea to create our own tools with Godot to assist our daily development.

### CODE REVIEW

**Comment by alfredbaudisch** [comment]
@CptFubar wow, that's an amazing and unexpected contribution! Thanks a lot!
As soon as I allocate some free time, I'll review and then merge it. 

> I hope this project is still alive and will see further development.

Development has not been activte for some time, but it's definitely alive, I'm always here. I've been just delaying adding the final features forever, but eventually they may be added. But more alive than ever, now with your contribution ❤️ .

**Comment by CptFubar** [comment]
I'm glad to hear that it is still alive and going strong. I'll be available for any questions or clarifications. 
As i mentioned before i branched and implemented a version with a local [backend ](https://github.com/cptfubar/Godello/tree/backend_local) alongside with the existing elixr implementation.
If there is any interest i can add another pull request for a branch with a local data storage (solution using custom resources).

**Comment by alfredbaudisch** [comment]
Those would be welcome too, @CptFubar !

**Comment by alfredbaudisch** [comment]
All good, @CptFubar . I just fixed some small things.

For example, you set debug messages as:
`print("board_model.gd:33 : card with id %d not found" % card.id)`

They both assume a fixed line number and a integer id. But ids can be string (for example UUID) and line numbers always change. So I changed all of those prints to comply with that.

But other than that, everything seems all good. Thanks for the contribution!

**Pull request merged**
